### ISSUE TITLE
Naming issue: The Cilk language

### ISSUE THREAD

**Issue by nekketsuuu** [maekawatoshiki/cilk#10]
Disclaimer: I have nothing to do with the Cilk language.

----

I noticed that this compiler infrastructure has the same name as the Cilk programming language, which is released in the 1990s: <https://en.wikipedia.org/wiki/Cilk>.

This can be a bit confusing because there are currently two "Cilk"s in the field of compiler implementation. But the confusion should be a little because one is a language and the other is a tool for compilers.

My question is: Have you already discussed this naming issue? If you've already done so, please just close this issue. If not, I think it is a good idea to consider this issue before your Cilk becomes more famous :)

**Comment by maekawatoshiki** [comment]
Originally I named this project by randomly typing on keyboard. (Thus I didn't know the Cilk in the 1990s.)
I agree with renaming this project. I consider another name before long.

**Comment by nekketsuuu** [comment]
Wow. Then I should have created this issue more earlier.... Re-naming is one of tough things. I hope everything goes well.

**Comment by maekawatoshiki** [comment]
Cilk is renamed Sericum! :tada:

**Comment by nekketsuuu** [comment]
Awesome! Thank you for your gentle response.
