### ISSUE TITLE
JavaScript-like front-end for cilk.

### ISSUE THREAD

**Issue by sisshiki1969** [maekawatoshiki/cilk#3]
I am working on a compiler which converts JavaScript source code to cilk-IR and execute.
https://github.com/sisshiki1969/rapidus-cilk
Be aware that `cilk` folder is empty, so git clone here before execution.

#### limitation
- Currently, only integer is supported.
- All variables must be declared using `let`.
- Can not refer external variables (variables declared outside of the function).
- A block scope is not yet implemented. (Function scope only)
- Can use `console.log()` to print.

#### sample code
```javascript
function fibo(x) {
  if (x == 1) {
    return 1
  } else if (x == 2) {
    return 1
  } else {
    return fibo_sub(x - 1, x - 2)
  }
  // function in function
  function fibo_sub(x, y) {
    return fibo(x) + fibo(y)
  }
}

let x = fibo(10)
console.log(x)
return x
```
```javascript
function prime(n) {
  if (n % 2 == 0) return 0
  for (let k = 3; k * k <= n; k += 2) { if (n % k == 0) return 0 }
  return 1
}

let max = 2

for (let i = 2; i <= 20; i += 1) {
  if (prime(i) == 1) {
    console.log(i)
    max = i
  }
}

return max
```
```javascript
let x = 0
while (x <= 8) {
  x += 1
}
console.log(x)
return x
```

**Comment by maekawatoshiki** [comment]
Amazing
