### ISSUE TITLE
Better DAG handling 

### ISSUE THREAD

**Issue by maekawatoshiki** [maekawatoshiki/cilk#5]
Currently, DAG nodes are managed using id_arena. However, it's troblesome to write code like ``arena[id].sth``, which should be written like ``node.sth``. 
So I'm planning to use raw pointer to take around dag nodes. (it's unsafe though)
Are there better ideas?

**Comment by sisshiki1969** [comment]
How about this?
My idea has two points, wrapping raw pointers using New type pattern, and implement Deref and DerefMut Trait for handling them without unsafe dereferencing. (Unsafe methods are enclosed in  Impl. methods)

```Rust
fn main() {
    let noderef = NodeRef::new(42);
    println!("{}", noderef.id);
}

pub struct Node {
    id: u32,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct NodeRef(*mut Node);
```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=13dc7fcdac2cc76fe950312d2df55b94

**Comment by maekawatoshiki** [comment]
Good idea. Such implementation is already used. (https://github.com/maekawatoshiki/cilk/blob/new-regalloc/src/util/allocator.rs)

**Comment by maekawatoshiki** [comment]
So I'm finding a better way if it exists.

**Comment by sisshiki1969** [comment]
Is this tweet about your implementation of Raw struct?
https://twitter.com/uint256_t/status/1189558608544927744

**Comment by maekawatoshiki** [comment]
Yes, but what's the matter with it?

**Comment by sisshiki1969** [comment]
I have encountered the very same problem recently...
