### ISSUE TITLE
About `cargo test --doc`

### ISSUE THREAD

**Issue by Drumato** [maekawatoshiki/cilk#7]
I pushed some commits (that add some doc-comment to `src/ir/module.rs` experimentally) under `docs` branch,  
but `cargo test --doc`not worked yet because some files occurs `fail to resolve` error while compilation.    
cilk must fix this Inconsistency first, for expecting efficiently tests

What do you think?

`docs` ブランチを切ってdoc-commentをいくつか書いてみました．  
しかし現状cilkで `cargo test [--doc]` が失敗するため，`docs.rs` ページのビルドも失敗する という問題があります．  

そこで，私に｢`cargo test` によって発生するバグたちを潰す作業｣ をやらせてもらえませんか?  
コンパイルエラーを削除することができればdocs.rsも生えて，使ってくれる人も増えるはず．  
(TODOにテスト書きたいというのもあったので，そのままユニットテストを書くのもやっていこうかな?と思っています)

**Comment by maekawatoshiki** [comment]
``cargo test --docs`` fails because you didn't specify features. I think it's not a 'bug.'
Anyway, I appreciate your contribution to making documents.

**Comment by Drumato** [comment]
Thanks for your responding rapidly.  
I'll continue to make documents.  
please teach me if you find any bad things in documents.

**Comment by Drumato** [comment]
Should I close this issue?

**Comment by maekawatoshiki** [comment]
yes, plz
