### ISSUE TITLE
[Feature request] Code patching

### ISSUE THREAD

**Issue by playXE** [maekawatoshiki/cilk#8]
This is a really useful feature for engines that do inline caching. Simple branch and call patching might be enough

**Comment by maekawatoshiki** [comment]
Thank you for being interested in cilk.
Code patching is worth implementing. However, cilk is basically a compiler infrastructure for static compiling. Such function for dynamic compiling is not what I've expected.
Anyway, it's interesting to support features for dynamically compiled languages.
